// frontend/components/ui/Label.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';

export type LabelProps = React.LabelHTMLAttributes<HTMLLabelElement>;

export function Label({ className, children, ...rest }: LabelProps) {
	return (
		<label
			className={cn('block text-[12px] font-medium mb-1.5 text-[var(--n-fg-muted)]', className)}
			{...rest}
		>
			{children}
		</label>
	);
}

export default Label;

// frontend/src/lib/components/ui/label.svelte
<script lang="ts">
	import type { HTMLLabelAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';

	interface Props extends HTMLLabelAttributes {
		class?: string;
	}

	let { class: klass = '', children, ...rest }: Props = $props();
</script>

<label
	class={cn('block text-[12px] font-medium mb-1.5 text-[var(--n-fg-muted)]', klass)}
	{...rest}
>
	{@render children?.()}
</label>
